user:
  shell: /bin/zsh

base_packages:
  - git
  - curl
  - build-essential

cloud:
  aws: true
  gcloud: true
  kubectl: true
  docker: true
  terraform: true

languages:
  go:
    enabled: true
    version: latest
    tools:
      - golangci-lint
      - gopls
      - delve

  node:
    enabled: true
    version: lts
    package_manager: pnpm
    global_packages:
      - typescript
      - prettier
      - eslint

shell:
  zsh: true
  oh_my_zsh: true
  tmux: true

claude:
  enabled: true
  allow:
    - gh
  deny: []
  ask: []
  mcp_servers:
    - name: "playwright"
      package: "@playwright/mcp"
      command: "npx"
      args:
        - "-y"
        - "@playwright/mcp"
      env: {}
    - name: "github"
      package: "github-mcp-server"
      command: "npx"
      args:
        - "-y"
        - "github-mcp-server"
      env: {}
    - name: "linear"
      package: "@mseep/linear-mcp"
      command: "npx"
      args:
        - "-y"
        - "@mseep/linear-mcp"
      env: {}

sessions:
  max_terminals: 10
  auto_reconnect_interval: 10s
  shell: "bash"
