// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package ui

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Menubar() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<nav class=\"menubar\"><div class=\"logo\">StratusShell</div><div class=\"dropdown\"><button class=\"dropdown-btn\">Layout ▾</button><div class=\"dropdown-menu\"><a hx-post=\"/api/layout/horizontal\" hx-target=\"#terminal-container\">Horizontal Split</a> <a hx-post=\"/api/layout/vertical\" hx-target=\"#terminal-container\">Vertical Split</a> <a hx-post=\"/api/layout/grid\" hx-target=\"#terminal-container\">Grid (2x2)</a></div></div><div class=\"dropdown\"><button class=\"dropdown-btn\">Config ▾</button><div class=\"dropdown-menu\"><a hx-get=\"/api/config/modal\" hx-target=\"#modal\">Preferences...</a> <a hx-post=\"/api/terminals/add\" hx-target=\"#terminal-container\">Add Terminal</a></div></div><div class=\"dropdown\"><button class=\"dropdown-btn\">Sessions ▾</button><div class=\"dropdown-menu\"><a hx-get=\"/api/session/save-modal\" hx-target=\"#modal\">Save Session...</a> <a hx-get=\"/api/session/list-modal\" hx-target=\"#modal\">Load Session...</a></div></div></nav>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
